- hosts: all
  name: Installation de Prometheus
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_targets:
      node:
        - targets:
            - "{{ hostvars['prometheus']['ansible_host'] }}:9100"
            - node.demo.do.prometheus.io
          labels:
            env: demosite

- hosts: all
  name: install node_exporter
  roles:
    - prometheus.prometheus.node_exporter
